Feature user modules
Houtaroy/ant-design-vue-pro pull request #11
Opened 2021-12-02 09:29 UTC by zhangxincccc

First of all, thank you for your contribution! 😄

Pull request will be merged after one of collaborators approve.
Please makes sure that these form are filled before submitting your pull request, thank you!

### 这个变动的性质是
- [ ] 重构

### 需求背景

左侧部门树 修改为 部门组织混合树 新增编辑增加所属组织条件 增加批量启用 停用删除按钮

### 实现方案和 API（非新功能可选）

。

### 对用户的影响和可能的风险（非新功能可选）

### Changelog 描述（非新功能可选）

### 请求合并前的自查清单

- [ ] Changelog 已提供或无须提供

### 后续计划（非新功能可选）

> 如果这个提交后面还有相关的其他提交和跟进信息，可以写在这里。

2021-12-02 13:26 UTC, Houtaroy requested changes
简单的问题直接修改, 复杂的值得讨论一下, 有些设计上的问题

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +        <department-list ref="childComponent" @getDepartmentData="getDepartmentData"></department-list>
混合树组件不应该叫department-list

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +                    <a-input v-model="userTableParam.userName" placeholder="请输入" allowClear />
userTableParam命名存在歧义

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +                    <a-range-picker allowClear v-model="userTableParam.userDate" />
查询条件中的相关属性应和接口实体对应一致

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +import { validateEmail } from '../../utils/validator';
验证规则和表单验证应该分离开

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      advanced: false, // 控制搜索条件的展开折叠
命名有歧义

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      addOrEdit: 1, // 判断新增或编辑（1为新增2为编辑）
可以用是否存在id判断是新增还是编辑

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      formUserVisible: false, // 控制表单弹框
命名有歧义, 没有体现出**弹窗**

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      formRoleArray: [], // 表单角色下拉数组
他们的区别是什么?

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      },
应和接口实体属性对应

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      },
可以用通用的工厂方法去生成这些规则

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      organizationsFormTreeData: [], // 组织下拉选择树结构数据
命名有问题, 如果是表单中的部门下拉数据, 可以命名为formDepartmentTreeData

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +    }
这里必须这么写吗?感觉很怪

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      this.batchSelectIdArr = selectedRowKeys;
不推荐使用Arr, 可以用ids或者idArray代替, 不要简写

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +    },
不太明白这的目的是干什么

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      });
太冗余, 为什么不让条件一一对应呢?

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +    },
方法命名有问题

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +          };
为什么不写成一一对应的表单对象呢

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +    getCurrentPage(pageNumber) {
方法命名有问题

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +    onShowSizeChange(currentPage, pageSize) {
应该是onPageSizeChange吧?

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +    },
接口增加了是否启用条件, 再讨论下需求

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +      }
没必要的if

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +    },
表单对象不统一的问题

2021-12-02 13:26 UTC, Houtaroy commented on src/views/system/user.vue
> +    }
处理不是很优雅

2021-12-06 09:54 UTC, zhangxincccc commented
关闭

2021-12-06 09:55 UTC, zhangxincccc commented
.

2021-12-06 11:18 UTC, Houtaroy requested changes
有些东西需要讨论修改

2021-12-06 11:18 UTC, Houtaroy commented on src/views/system/components/tree/mixTreeData.vue
>      },
整体搜索逻辑有问题, 搜索的目的是为了找到所有应该展开的节点id, 为什么要用this.selectIdArray保存?直接声明一个局部变量不可以吗?

2021-12-06 11:18 UTC, Houtaroy commented on src/views/system/components/tree/mixTreeData.vue
>        }
为什么要提交出去id, 直接用rowData中的内容不可以吗

2021-12-06 11:18 UTC, Houtaroy commented on src/views/system/user.vue
> +          ref="childComponent"
ref命名不对

2021-12-06 11:18 UTC, Houtaroy commented on src/views/system/user.vue
> +                    <a-input v-model="userTableSearchParam.searchName" placeholder="请输入" allowClear />
在用户页面内部, 可以使用searchParameters, 不会有歧义

2021-12-06 11:18 UTC, Houtaroy commented on src/views/system/user.vue
> +            this.getUserTableData(this.pageObject, this.userTableSearchParam);
停用启用这里可以不用重新查接口

2021-12-06 11:18 UTC, Houtaroy commented on src/views/system/user.vue
> +    getUserDepartmentTree(searchOrganizationId) {
参数命名不对, 直接是searchParameters就可以了

2021-12-06 11:18 UTC, Houtaroy commented on src/views/system/user.vue
> +    searchUserTableComponentParams() {
这里应该是搜索方法, 直接命名search就可以了吧?

2021-12-07 02:27 UTC, zhangxincccc commented on src/views/system/user.vue
> +    searchUserTableComponentParams() {
这里是搜索的公共参数请求代码 所以取了componentParams

2021-12-07 05:48 UTC, Houtaroy requested changes
大部分是命名问题, 还有一部分代码逻辑问题

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/components/tree/OrganizationMixTree.vue
> +      selectMixTreeArray: [], // 树结构选中的数据
这两个变量可以删除

2021-12-07 05:48 UTC, Houtaroy commented on vue.config.js
> +const url = 'http://localhost:9998';
不应该修改为9998

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +      <div class="departmentList">
class名称不对

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +          @cancelSelect="cancelSelectMixTreeDepartmentData"
应该是cancelSelectMixTreeData吧?

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +    onSelectChange(selectedRowKeys) {
改成handleUserSelectChange会不会好一点?

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +    getUserRoleData() {
应该是getRoles吧?获取全部角色

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +    searchUserTableComponentParams() {
不对啊, 你这里最后调用了搜索用户数据, 这个方法应该是查询用户信息的含义

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +    },
这里应该是批量处理完成后的操作, 可以叫afterBatchActions一类的, 这里不存在组件为什么要叫Component呢?

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +    getPageNumber(pageNumber) {
这里是页面变化后的操作, 应该叫onPageNumberChange或者handlePageNumberChange

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +    },
这种操作应该在混合树的组件内部做, 为什么要放到外面来呢?

2021-12-07 05:48 UTC, Houtaroy commented on src/views/system/user.vue
> +    },
1.编辑的时候应该调用load接口从后台查询数据
2.对于department这种下拉选择的属性, 可以做进一步的处理

2021-12-07 08:36 UTC, Houtaroy requested changes
小问题调整一下

2021-12-07 08:36 UTC, Houtaroy commented on src/views/system/components/tree/OrganizationMixTree.vue
> +    <div class="departmentListSearch">
class命名

2021-12-07 08:36 UTC, Houtaroy commented on src/views/system/components/tree/OrganizationMixTree.vue
> +    <div class="departmentListContent">
class命名

2021-12-07 08:36 UTC, Houtaroy commented on src/views/system/components/tree/OrganizationMixTree.vue
> +        }
可以简写成`item.disabled = item.isEnable === 0`

2021-12-07 08:36 UTC, Houtaroy commented on src/views/system/user.vue
> +          });
这里可不可以改成下面这样会好一点?
```js
this.form.roleIds = this.form.roles.map(item => {
  return item.id;
})
```

2021-12-07 11:18 UTC, merged